WIP: Use non default ports
RedHat-SP-Security/keylime-tests pull request #197
Opened 2022-09-08 12:45 UTC by Koncpa

Keylime mainly use default ports set in
configuration file. Set non default ports
and check if keylime work on basic
functionality properly.

#130

2022-10-18 12:47 UTC, kkaarreell requested changes

2022-10-18 12:47 UTC, kkaarreell commented on functional/keylime-non-default-ports/test.sh
> +    rlPhaseStartTest "Fail keylime agent - setting wrong ports"
What is this scenario supposed to do/test?

2022-10-18 12:47 UTC, kkaarreell commented on functional/keylime-non-default-ports/test.sh
> +        rlRun "kill ${HTTP_SERVER_PID}"
remove HTTP_SERVER related stuff

2022-10-18 12:47 UTC, kkaarreell commented on functional/keylime-non-default-ports/test.sh
> +        HTTP_SERVER_LOG=$( mktemp )
remove HTTP_SERVER and ncat related stuff, it is not necessary for this test

2022-10-18 12:47 UTC, kkaarreell commented on functional/keylime-non-default-ports/main.fmf
> +    Running verifier and registrar with wrong ports.
Not sure if this last scenario is really useful. What would it prove?

2022-10-18 12:47 UTC, kkaarreell commented on functional/keylime-non-default-ports/test.sh
> +            cat ${HTTP_SERVER_LOG}
remove all HTTP_SERVER related stuff

2022-10-21 05:59 UTC, kkaarreell commented on functional/keylime-non-default-ports/main.fmf
> +    Change all default ports to non default ports.
Change ports used by keylime services to non default ports ...

2022-10-21 06:02 UTC, kkaarreell commented
@Koncpa I am wondering, can we expect this test to fail when running it with keylime SELinux policy? If yes, maybe we would want to tweak it a bit.

2022-10-21 07:19 UTC, Koncpa commented
> @Koncpa I am wondering, can we expect this test to fail when running it with keylime SELinux policy? If yes, maybe we would want to tweak it a bit.

I'll try run this test with selinux policy and we'll see.

2022-10-21 12:21 UTC, Koncpa commented
> @Koncpa I am wondering, can we expect this test to fail when running it with keylime SELinux policy? If yes, maybe we would want to tweak it a bit.

It seems, that test pass also with keylime SELinux policy. I merge then this PR.

2022-10-21 12:43 UTC, kkaarreell approved these changes

2022-10-21 12:44 UTC, merged