Provide public key for signature verification on command line
RedHat-SP-Security/keylime-tests pull request #562
Opened 2024-03-19 12:52 UTC by stefanberger

Keylime does not allow the trivial passing of signature verification on the self-signed certificate embedded in the DSSE envelope of a signed policy anymore. Instead, it requires that a public key for signature verification be given by the user. Therefore, pass the public key needed for signature verification via the command line.

This PR requires agreement on https://github.com/keylime/keylime/pull/1482

2024-03-19 13:41 UTC, kkaarreell requested changes
Hello, thank you for the proposed update. I have just two nitpicks.
Btw, there are some recent changes breaking our tests, I am currently working on fixes but something are regressions in keylime and rust-keylime.

2024-03-19 13:41 UTC, kkaarreell commented on Library/test-helpers/lib.sh
> +    openssl ec -in dsse-x509-privkey.key -pubout -out dsse-x509-pubkey.pub
Please, add `&& \` at the end of the previous line.

2024-03-19 13:41 UTC, kkaarreell commented on functional/tenant-runtime-policy-sanity/test.sh
> +        rlRun -s "keylime_tenant -c addruntimepolicy --runtime-policy-name list7 --runtime-policy-sig-key dsse-x509-pubkey.pub --runtime-policy-url 'http://localhost:8000/policy-dsse-x509.json' --run
Extra spaces at the end of the string.

2024-03-19 13:59 UTC, stefanberger commented
> Hello, thank you for the proposed update. I have just two nitpicks.

Fixed.

> Btw, there are some recent changes breaking our tests, I am currently working on fixes but something are regressions in keylime and rust-keylime.

I saw only breakages in rawhide yesterday, the rest was fine.

2024-03-19 14:45 UTC, kkaarreell commented
> I saw only breakages in rawhide yesterday, the rest was fine.

In keylime-tests repository CI we are running few more tests that are not being run in keylime upstream.
I am trying to address it partially in https://github.com/keylime/keylime/pull/1535

2024-03-20 07:49 UTC, kkaarreell commented
Test results looks as expected:
 - failure in /regression/CVE-2023-3674 is due to https://github.com/keylime/keylime/issues/1534, will be fixed with https://github.com/keylime/keylime/pull/1537
 - failure in /container/functional/keylime_ipv6_multihost is due to https://github.com/keylime/rust-keylime/issues/763
 - failure in /functional/install-rpm-with-ima-signature will be fixed with https://github.com/RedHat-SP-Security/keylime-tests/pull/561

2024-03-20 07:49 UTC, kkaarreell approved these changes

2024-03-20 07:50 UTC, kkaarreell commented
Hi @stefanberger , are you OK with the current state? Since it does not interfere with the keylime upstream code I would merge it.

2024-03-20 08:31 UTC, Koncpa approved these changes

2024-03-21 18:11 UTC, stefanberger commented
Someone other than me needs to merge this due to authorization requirements. I will then remove the top-most patch from https://github.com/keylime/keylime/pull/1482 and merge that one then.

2024-03-21 18:33 UTC, merged