Update basic-attestation-on-localhost-api-version-bump for the agent with multiple API
RedHat-SP-Security/keylime-tests pull request #688
Opened 2024-12-19 17:11 UTC by ansasaki

Replace the re-compilation of the agent using an older version with a simple
reconfiguration of  the agent enabling the desired API version.

2024-12-20 13:05 UTC, ansasaki commented
/packit retest-failed

2025-01-02 13:39 UTC, kkaarreell commented on compatibility/basic-attestation-on-localhost-api-version-bump/test.sh
> +            rlDie "Agent supports only one API version"
Please, do not use `rlDie` as the test won't do a cleanup. Rather `rlFail` and conditionally skip other test phases.

2025-01-02 13:41 UTC, kkaarreell commented on compatibility/basic-attestation-on-localhost-api-version-bump/test.sh
> -        rlAssertGrep "Starting server with API version v${OLD_VERSION}" "$(limeAgentLogfile)" -E
It would be nice to be able to verify that the agent is truly starting with the OLD version. Can we keep it in place or is the message no longer present?

2025-01-02 13:42 UTC, kkaarreell requested changes
Thank you for test updates. I have two small change requests.

2025-01-02 15:45 UTC, ansasaki commented on compatibility/basic-attestation-on-localhost-api-version-bump/test.sh
> +            rlDie "Agent supports only one API version"
OK, I did not know that `rlDie` skipped the cleanup phase. I replaced it with `rlFail`

2025-01-02 15:46 UTC, ansasaki commented on compatibility/basic-attestation-on-localhost-api-version-bump/test.sh
> -        rlAssertGrep "Starting server with API version v${OLD_VERSION}" "$(limeAgentLogfile)" -E
I re-added the check.

2025-01-02 22:36 UTC, kkaarreell commented on compatibility/basic-attestation-on-localhost-api-version-bump/test.sh
> -        rlAssertGrep "Starting server with API version v${OLD_VERSION}" "$(limeAgentLogfile)" -E
I am not 100% sure but I think that the `limeWaitForAgentRegistration ` call was there to ensure that the grep is not executed too early. Let's see how tests will work.

2025-01-02 22:39 UTC, kkaarreell approved these changes
LGTM.

2025-01-06 10:36 UTC, Koncpa approved these changes

2025-01-10 09:16 UTC, merged